/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package source;

import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import static source.MainWindow.usersList;

/**
 *
 * @author Raul Farkas
 */
public class AdminSignaturesListPanel extends javax.swing.JPanel {

    private DefaultListModel listModel = new DefaultListModel();
    LocalDate ld;

    /**
     * Creates new form AdminSignaturesListPanel
     */
    public AdminSignaturesListPanel() {
        //Get signatures for today
        ld = LocalDate.now();
        for (Signature s : MainWindow.signatureList.getList()) {
            if (s.getDateTime().isAfter(ld.atStartOfDay())) {
                listModel.addElement(s.getUser().getUsername()+ " " + s.getDateTime().format(DateTimeFormatter.ofPattern("hh:mm:ss")));
            }
        }
        initComponents();
        welcomeLabel.setText("Welcome, " + MainWindow.session.getUser().getUsername());
        if(ld.atStartOfDay().equals(LocalDate.now().atStartOfDay())){
            todayLabel.setText("Today: " + ld.format(DateTimeFormatter.ofPattern("dd-MM-YYYY")));
        }else{
            todayLabel.setText(ld.format(DateTimeFormatter.ofPattern("dd-MM-YYYY")));
        }
    }

    /**
     *
     * @param date
     */
    public AdminSignaturesListPanel(LocalDate date) {
        //Get signatures for a specific date
        ld = date;
        for (Signature s : MainWindow.signatureList.getList()) {
            if (s.getDateTime().isAfter(date.atStartOfDay()) && s.getDateTime().isBefore(date.atTime(23, 59))) {
                listModel.addElement(s.getUser().getUsername()+ " " + s.getDateTime().format(DateTimeFormatter.ofPattern("hh:mm:ss")));
            }
        }
        initComponents();
        welcomeLabel.setText("Welcome, " + MainWindow.session.getUser().getUsername());
        if(ld.atStartOfDay().equals(LocalDate.now().atStartOfDay())){
            todayLabel.setText("Today: " + ld.format(DateTimeFormatter.ofPattern("dd-MM-YYYY")));
        }else{
            todayLabel.setText(ld.format(DateTimeFormatter.ofPattern("dd-MM-YYYY")));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        goToProfileButton1 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(500, 0), new java.awt.Dimension(500, 0), new java.awt.Dimension(20, 70));
        jPanel1 = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 300), new java.awt.Dimension(0, 300), new java.awt.Dimension(415, 300));
        previousDayButton = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 300), new java.awt.Dimension(0, 300), new java.awt.Dimension(30, 300));
        todayLabel = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 300), new java.awt.Dimension(0, 300), new java.awt.Dimension(30, 300));
        logOutButton2 = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 300), new java.awt.Dimension(0, 300), new java.awt.Dimension(415, 300));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(500, 0), new java.awt.Dimension(500, 0), new java.awt.Dimension(20, 50));
        todayLabel1 = new javax.swing.JLabel();
        signedReference = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        signaturesList = new javax.swing.JList<>();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 100));
        backButton = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 100));

        setMaximumSize(new java.awt.Dimension(1920, 720));
        setMinimumSize(new java.awt.Dimension(1920, 720));

        mainPanel.setBackground(new java.awt.Color(63, 81, 181));
        mainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPanel.setDoubleBuffered(false);
        mainPanel.setMaximumSize(new java.awt.Dimension(1280, 720));
        mainPanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.Y_AXIS));

        topPanel.setBackground(new java.awt.Color(63, 81, 181));
        topPanel.setAlignmentY(0.0F);
        topPanel.setMaximumSize(new java.awt.Dimension(1330, 100));

        welcomeLabel.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setText("Welcome");
        welcomeLabel.setAlignmentY(0.0F);

        logOutButton.setBackground(new java.awt.Color(0, 59, 142));
        logOutButton.setForeground(new java.awt.Color(255, 255, 255));
        logOutButton.setText("LogOut");
        logOutButton.setBorder(null);
        logOutButton.setBorderPainted(false);
        logOutButton.setMargin(null);
        logOutButton.setMaximumSize(new java.awt.Dimension(150, 30));
        logOutButton.setMinimumSize(new java.awt.Dimension(150, 30));
        logOutButton.setPreferredSize(new java.awt.Dimension(150, 30));
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonlogOut(evt);
            }
        });

        goToProfileButton1.setBackground(new java.awt.Color(0, 59, 142));
        goToProfileButton1.setForeground(new java.awt.Color(255, 255, 255));
        goToProfileButton1.setText("Profile");
        goToProfileButton1.setBorder(null);
        goToProfileButton1.setBorderPainted(false);
        goToProfileButton1.setMargin(null);
        goToProfileButton1.setMaximumSize(new java.awt.Dimension(150, 30));
        goToProfileButton1.setMinimumSize(new java.awt.Dimension(150, 30));
        goToProfileButton1.setPreferredSize(new java.awt.Dimension(150, 30));
        goToProfileButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToProfileButton1goToProfile(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(goToProfileButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                        .addGap(0, 1106, Short.MAX_VALUE)
                        .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel)
                    .addComponent(goToProfileButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(topPanel);
        mainPanel.add(filler1);

        jPanel1.setBackground(new java.awt.Color(63, 81, 181));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 100));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(filler5);

        previousDayButton.setBackground(new java.awt.Color(0, 59, 142));
        previousDayButton.setForeground(new java.awt.Color(255, 255, 255));
        previousDayButton.setText("Previous day");
        previousDayButton.setBorder(null);
        previousDayButton.setBorderPainted(false);
        previousDayButton.setMargin(null);
        previousDayButton.setMaximumSize(new java.awt.Dimension(150, 30));
        previousDayButton.setMinimumSize(new java.awt.Dimension(150, 30));
        previousDayButton.setPreferredSize(new java.awt.Dimension(150, 30));
        previousDayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToPreviousDay(evt);
            }
        });
        jPanel1.add(previousDayButton);
        jPanel1.add(filler7);

        todayLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        todayLabel.setForeground(new java.awt.Color(255, 255, 255));
        todayLabel.setText("Today: ");
        todayLabel.setAlignmentX(0.5F);
        jPanel1.add(todayLabel);
        jPanel1.add(filler9);

        logOutButton2.setBackground(new java.awt.Color(0, 59, 142));
        logOutButton2.setForeground(new java.awt.Color(255, 255, 255));
        logOutButton2.setText("Next day");
        logOutButton2.setBorder(null);
        logOutButton2.setBorderPainted(false);
        logOutButton2.setMargin(null);
        logOutButton2.setMaximumSize(new java.awt.Dimension(150, 30));
        logOutButton2.setMinimumSize(new java.awt.Dimension(150, 30));
        logOutButton2.setPreferredSize(new java.awt.Dimension(150, 30));
        logOutButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToNextDay(evt);
            }
        });
        jPanel1.add(logOutButton2);
        jPanel1.add(filler6);

        mainPanel.add(jPanel1);
        mainPanel.add(filler2);

        todayLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        todayLabel1.setForeground(new java.awt.Color(255, 255, 255));
        todayLabel1.setText("Signatures:");
        todayLabel1.setAlignmentX(0.5F);
        mainPanel.add(todayLabel1);

        signedReference.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        signedReference.setForeground(new java.awt.Color(255, 255, 255));
        signedReference.setAlignmentX(0.5F);
        mainPanel.add(signedReference);

        jScrollPane2.setMaximumSize(new java.awt.Dimension(500, 450));

        signaturesList.setBackground(new java.awt.Color(117, 125, 232));
        signaturesList.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        signaturesList.setForeground(new java.awt.Color(255, 255, 255));
        signaturesList.setModel(listModel);
        jScrollPane2.setViewportView(signaturesList);

        mainPanel.add(jScrollPane2);
        mainPanel.add(filler3);

        backButton.setBackground(new java.awt.Color(0, 59, 142));
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.setAlignmentX(0.5F);
        backButton.setBorder(null);
        backButton.setBorderPainted(false);
        backButton.setMargin(null);
        backButton.setMaximumSize(new java.awt.Dimension(200, 50));
        backButton.setPreferredSize(new java.awt.Dimension(200, 50));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtongoToBack(evt);
            }
        });
        mainPanel.add(backButton);
        mainPanel.add(filler4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logOutButtonlogOut(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonlogOut
        try {

            MainWindow.session.setUser(null);
        } catch (IOException ex) {
            Logger.getLogger(HomePanelLoggedIn.class.getName()).log(Level.SEVERE, null, ex);
            JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            topFrame.getContentPane().removeAll();
            topFrame.getContentPane().add(new MainPanel());
            topFrame.pack();
            return;
        }

        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.getContentPane().removeAll();
        topFrame.getContentPane().add(new MainPanel());
        topFrame.pack();
        JOptionPane.showMessageDialog(null,
                "You logged out successfully!");
    }//GEN-LAST:event_logOutButtonlogOut

    private void goToProfileButton1goToProfile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToProfileButton1goToProfile
        // TODO add your handling code here:
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.getContentPane().removeAll();
        topFrame.getContentPane().add(new Profile());
        topFrame.pack();
    }//GEN-LAST:event_goToProfileButton1goToProfile

    private void backButtongoToBack(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtongoToBack
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.getContentPane().removeAll();
        topFrame.getContentPane().add(new AdminUsersAndSignaturesPanel());
        topFrame.pack();
    }//GEN-LAST:event_backButtongoToBack

    private void goToPreviousDay(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToPreviousDay
        // TODO add your handling code here:
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.getContentPane().removeAll();
        topFrame.getContentPane().add(new AdminSignaturesListPanel(ld.minusDays(1)));
        topFrame.pack();
    }//GEN-LAST:event_goToPreviousDay

    private void goToNextDay(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToNextDay
        // TODO add your handling code here:
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.getContentPane().removeAll();
        topFrame.getContentPane().add(new AdminSignaturesListPanel(ld.plusDays(1)));
        topFrame.pack();
    }//GEN-LAST:event_goToNextDay


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton goToProfileButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton logOutButton2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton previousDayButton;
    private javax.swing.JList<String> signaturesList;
    private javax.swing.JLabel signedReference;
    private javax.swing.JLabel todayLabel;
    private javax.swing.JLabel todayLabel1;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
