/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package source;

import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author raul
 */
public class AdminUserSignPresencePanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminUserSignPresencePanel
     */
    public AdminUserSignPresencePanel() {
        initComponents();
        welcomeLabel.setText("Welcome, " + MainWindow.session.getUser().getUsername());
        DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        todayLabel.setText("Today: " + formatter.format(new Date()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        goToProfileButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(500, 0), new java.awt.Dimension(500, 0), new java.awt.Dimension(20, 100));
        todayLabel = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(500, 0), new java.awt.Dimension(500, 0), new java.awt.Dimension(20, 70));
        signButton = new javax.swing.JButton();
        signedReference = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 50));
        adminToolsButton = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 50));

        setMaximumSize(new java.awt.Dimension(1780, 720));
        setMinimumSize(new java.awt.Dimension(1780, 720));

        mainPanel.setBackground(new java.awt.Color(63, 81, 181));
        mainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPanel.setDoubleBuffered(false);
        mainPanel.setMaximumSize(new java.awt.Dimension(1280, 720));
        mainPanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.Y_AXIS));

        topPanel.setBackground(new java.awt.Color(63, 81, 181));
        topPanel.setAlignmentY(0.0F);
        topPanel.setMaximumSize(new java.awt.Dimension(1330, 100));

        welcomeLabel.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setText("Welcome");
        welcomeLabel.setAlignmentY(0.0F);

        logOutButton.setBackground(new java.awt.Color(0, 59, 142));
        logOutButton.setForeground(new java.awt.Color(255, 255, 255));
        logOutButton.setText("LogOut");
        logOutButton.setBorder(null);
        logOutButton.setBorderPainted(false);
        logOutButton.setMargin(null);
        logOutButton.setMaximumSize(new java.awt.Dimension(150, 30));
        logOutButton.setMinimumSize(new java.awt.Dimension(150, 30));
        logOutButton.setPreferredSize(new java.awt.Dimension(150, 30));
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonlogOut(evt);
            }
        });

        goToProfileButton.setBackground(new java.awt.Color(0, 59, 142));
        goToProfileButton.setForeground(new java.awt.Color(255, 255, 255));
        goToProfileButton.setText("Profile");
        goToProfileButton.setBorder(null);
        goToProfileButton.setBorderPainted(false);
        goToProfileButton.setMargin(null);
        goToProfileButton.setMaximumSize(new java.awt.Dimension(150, 30));
        goToProfileButton.setMinimumSize(new java.awt.Dimension(150, 30));
        goToProfileButton.setPreferredSize(new java.awt.Dimension(150, 30));
        goToProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToProfileButtongoToProfile(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 977, Short.MAX_VALUE)
                        .addComponent(goToProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel)
                    .addComponent(goToProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(topPanel);
        mainPanel.add(filler1);

        todayLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        todayLabel.setForeground(new java.awt.Color(255, 255, 255));
        todayLabel.setText("Today: ");
        todayLabel.setAlignmentX(0.5F);
        mainPanel.add(todayLabel);
        mainPanel.add(filler2);

        signButton.setBackground(new java.awt.Color(0, 59, 142));
        signButton.setForeground(new java.awt.Color(255, 255, 255));
        signButton.setText("Sign presence");
        signButton.setAlignmentX(0.5F);
        signButton.setBorder(null);
        signButton.setBorderPainted(false);
        signButton.setMargin(null);
        signButton.setMaximumSize(new java.awt.Dimension(200, 50));
        signButton.setPreferredSize(new java.awt.Dimension(200, 50));
        signButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signButtonsignNow(evt);
            }
        });
        mainPanel.add(signButton);

        signedReference.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        signedReference.setForeground(new java.awt.Color(255, 255, 255));
        signedReference.setAlignmentX(0.5F);
        mainPanel.add(signedReference);
        mainPanel.add(filler3);

        adminToolsButton.setBackground(new java.awt.Color(0, 59, 142));
        adminToolsButton.setForeground(new java.awt.Color(255, 255, 255));
        adminToolsButton.setText("Admin Tools");
        adminToolsButton.setAlignmentX(0.5F);
        adminToolsButton.setBorder(null);
        adminToolsButton.setBorderPainted(false);
        adminToolsButton.setMargin(null);
        adminToolsButton.setMaximumSize(new java.awt.Dimension(200, 50));
        adminToolsButton.setPreferredSize(new java.awt.Dimension(200, 50));
        adminToolsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToAdminTools(evt);
            }
        });
        mainPanel.add(adminToolsButton);
        mainPanel.add(filler4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 500, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logOutButtonlogOut(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonlogOut
        try {

            MainWindow.session.setUser(null);
        } catch (IOException ex) {
            Logger.getLogger(HomePanelLoggedIn.class.getName()).log(Level.SEVERE, null, ex);
            JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            topFrame.getContentPane().removeAll();
            topFrame.getContentPane().add(new MainPanel());
            topFrame.pack();
            return;
        }

        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.getContentPane().removeAll();
        topFrame.getContentPane().add(new MainPanel());
        topFrame.pack();
        JOptionPane.showMessageDialog(null,
                "You logged out successfully!");
    }//GEN-LAST:event_logOutButtonlogOut

    private void goToProfileButtongoToProfile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToProfileButtongoToProfile
        // TODO add your handling code here:
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.getContentPane().removeAll();
        topFrame.getContentPane().add(new Profile());
        topFrame.pack();
    }//GEN-LAST:event_goToProfileButtongoToProfile

    private void signButtonsignNow(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signButtonsignNow
        try {
            try {
                // TODO add your handling code here:
                MainWindow.signatureList.signNow(MainWindow.session.getUser());
                JOptionPane.showMessageDialog(null,
                "You signed at: " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("hh.mm a\t dd/MM/yyyy"))+"\n successfully!");
            } catch (UserAlreadySignedException ex) {
                
                JOptionPane.showMessageDialog(null,
                        "You signed at: " + MainWindow.signatureList.getByUserToday(MainWindow.session.getUser().getUsername()).getDateTime().format(DateTimeFormatter.ofPattern("hh.mm a\t dd/MM/yyyy"))+"\nCan't do that again!",
                        "Inane error",
                        JOptionPane.ERROR_MESSAGE);

            }
        } catch (IOException ex) {
            Logger.getLogger(RegularUserSignPresencePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_signButtonsignNow

    private void goToAdminTools(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToAdminTools
        // TODO add your handling code here:
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.getContentPane().removeAll();
        topFrame.getContentPane().add(new AdminUsersAndSignaturesPanel());
        topFrame.pack();
    }//GEN-LAST:event_goToAdminTools


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminToolsButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JButton goToProfileButton;
    private javax.swing.JButton logOutButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton signButton;
    private javax.swing.JLabel signedReference;
    private javax.swing.JLabel todayLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables

}
