/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package source;

import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author raul
 */
public class AdminUsersListPanel extends javax.swing.JPanel {

    private DefaultListModel listModel = new DefaultListModel();

    /**
     * Creates new form AdminUsersListPanel
     */
    public AdminUsersListPanel() {
        //Load users list
        for (User user : MainWindow.usersList.getUsers()) {
            if (!user.getUsername().equals(MainWindow.session.getUser().getUsername())) {
                listModel.addElement(user.getUsername());
            }
        }

        initComponents();
        welcomeLabel.setText("Welcome, " + MainWindow.session.getUser().getUsername());
        DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        todayLabel.setText("Today: " + formatter.format(new Date()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        goToProfileButton1 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(500, 0), new java.awt.Dimension(500, 0), new java.awt.Dimension(20, 70));
        todayLabel = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(500, 0), new java.awt.Dimension(500, 0), new java.awt.Dimension(20, 50));
        todayLabel1 = new javax.swing.JLabel();
        signedReference = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        usersList = new javax.swing.JList<>();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 100));
        backButton = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 100));

        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        mainPanel.setBackground(new java.awt.Color(63, 81, 181));
        mainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPanel.setDoubleBuffered(false);
        mainPanel.setMaximumSize(new java.awt.Dimension(1280, 720));
        mainPanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.Y_AXIS));

        topPanel.setBackground(new java.awt.Color(63, 81, 181));
        topPanel.setAlignmentY(0.0F);
        topPanel.setMaximumSize(new java.awt.Dimension(1330, 100));

        welcomeLabel.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setText("Welcome");
        welcomeLabel.setAlignmentY(0.0F);

        logOutButton.setBackground(new java.awt.Color(0, 59, 142));
        logOutButton.setForeground(new java.awt.Color(255, 255, 255));
        logOutButton.setText("LogOut");
        logOutButton.setBorder(null);
        logOutButton.setBorderPainted(false);
        logOutButton.setMargin(null);
        logOutButton.setMaximumSize(new java.awt.Dimension(150, 30));
        logOutButton.setMinimumSize(new java.awt.Dimension(150, 30));
        logOutButton.setPreferredSize(new java.awt.Dimension(150, 30));
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonlogOut(evt);
            }
        });

        goToProfileButton1.setBackground(new java.awt.Color(0, 59, 142));
        goToProfileButton1.setForeground(new java.awt.Color(255, 255, 255));
        goToProfileButton1.setText("Profile");
        goToProfileButton1.setBorder(null);
        goToProfileButton1.setBorderPainted(false);
        goToProfileButton1.setMargin(null);
        goToProfileButton1.setMaximumSize(new java.awt.Dimension(150, 30));
        goToProfileButton1.setMinimumSize(new java.awt.Dimension(150, 30));
        goToProfileButton1.setPreferredSize(new java.awt.Dimension(150, 30));
        goToProfileButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToProfileButton1goToProfile(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(goToProfileButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                        .addGap(0, 1106, Short.MAX_VALUE)
                        .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel)
                    .addComponent(goToProfileButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(topPanel);
        mainPanel.add(filler1);

        todayLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        todayLabel.setForeground(new java.awt.Color(255, 255, 255));
        todayLabel.setText("Today: ");
        todayLabel.setAlignmentX(0.5F);
        mainPanel.add(todayLabel);
        mainPanel.add(filler2);

        todayLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        todayLabel1.setForeground(new java.awt.Color(255, 255, 255));
        todayLabel1.setText("Users:");
        todayLabel1.setAlignmentX(0.5F);
        mainPanel.add(todayLabel1);

        signedReference.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        signedReference.setForeground(new java.awt.Color(255, 255, 255));
        signedReference.setAlignmentX(0.5F);
        mainPanel.add(signedReference);

        jScrollPane2.setMaximumSize(new java.awt.Dimension(500, 450));

        usersList.setBackground(new java.awt.Color(117, 125, 232));
        usersList.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        usersList.setForeground(new java.awt.Color(255, 255, 255));
        usersList.setModel(listModel);
        usersList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectElement(evt);
            }
        });
        jScrollPane2.setViewportView(usersList);

        mainPanel.add(jScrollPane2);
        mainPanel.add(filler3);

        backButton.setBackground(new java.awt.Color(0, 59, 142));
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.setAlignmentX(0.5F);
        backButton.setBorder(null);
        backButton.setBorderPainted(false);
        backButton.setMargin(null);
        backButton.setMaximumSize(new java.awt.Dimension(200, 50));
        backButton.setPreferredSize(new java.awt.Dimension(200, 50));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToBack(evt);
            }
        });
        mainPanel.add(backButton);
        mainPanel.add(filler4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logOutButtonlogOut(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonlogOut
        try {

            MainWindow.session.setUser(null);
        } catch (IOException ex) {
            Logger.getLogger(HomePanelLoggedIn.class.getName()).log(Level.SEVERE, null, ex);
            JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            topFrame.getContentPane().removeAll();
            topFrame.getContentPane().add(new MainPanel());
            topFrame.pack();
            return;
        }

        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.getContentPane().removeAll();
        topFrame.getContentPane().add(new MainPanel());
        topFrame.pack();
        JOptionPane.showMessageDialog(null,
                "You logged out successfully!");
    }//GEN-LAST:event_logOutButtonlogOut

    private void selectElement(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectElement
        //Select element from list
        String selectedValue = usersList.getSelectedValue();
        if (selectedValue != null) {
         
            JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            topFrame.getContentPane().removeAll();
            topFrame.getContentPane().add(new AdminUserProfileViewPanel(MainWindow.usersList.getByUsername(selectedValue)));
            topFrame.pack();
        }

    }//GEN-LAST:event_selectElement

    private void goToProfileButton1goToProfile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToProfileButton1goToProfile
        // TODO add your handling code here:
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.getContentPane().removeAll();
        topFrame.getContentPane().add(new Profile());
        topFrame.pack();
    }//GEN-LAST:event_goToProfileButton1goToProfile

    private void goToBack(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToBack
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.getContentPane().removeAll();
        topFrame.getContentPane().add(new AdminUsersAndSignaturesPanel());
        topFrame.pack();
    }//GEN-LAST:event_goToBack


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JButton goToProfileButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logOutButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel signedReference;
    private javax.swing.JLabel todayLabel;
    private javax.swing.JLabel todayLabel1;
    private javax.swing.JPanel topPanel;
    private javax.swing.JList<String> usersList;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
