/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package source;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author raul
 */
public class RegisterPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterPanel
     */
    public RegisterPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 70));
        credentialsPanel = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 50));
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(300, 0), new java.awt.Dimension(300, 0), new java.awt.Dimension(200, 70));
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(300, 0), new java.awt.Dimension(300, 0), new java.awt.Dimension(200, 70));
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 40));
        buttonsPanel = new javax.swing.JPanel();
        registerButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        mainPanel.setBackground(new java.awt.Color(63, 81, 181));
        mainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPanel.setDoubleBuffered(false);
        mainPanel.setMaximumSize(new java.awt.Dimension(1280, 720));
        mainPanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.Y_AXIS));

        topPanel.setBackground(new java.awt.Color(63, 81, 181));
        topPanel.setAlignmentY(0.0F);
        topPanel.setMaximumSize(new java.awt.Dimension(1330, 100));

        welcomeLabel.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setText("Welcome");
        welcomeLabel.setAlignmentY(0.0F);

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel)
                .addContainerGap(1139, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        mainPanel.add(topPanel);
        mainPanel.add(filler1);

        credentialsPanel.setBackground(new java.awt.Color(63, 81, 181));
        credentialsPanel.setBorder(null
        );
        credentialsPanel.setMaximumSize(new java.awt.Dimension(600, 300));
        credentialsPanel.setLayout(new javax.swing.BoxLayout(credentialsPanel, javax.swing.BoxLayout.Y_AXIS));
        credentialsPanel.add(filler4);

        usernameLabel.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("Username");
        usernameLabel.setAlignmentX(0.5F);
        credentialsPanel.add(usernameLabel);

        usernameField.setBackground(new java.awt.Color(117, 125, 232));
        usernameField.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        usernameField.setForeground(new java.awt.Color(255, 255, 255));
        usernameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameField.setToolTipText("Username");
        usernameField.setBorder(null);
        usernameField.setMaximumSize(new java.awt.Dimension(250, 40));
        usernameField.setMinimumSize(new java.awt.Dimension(250, 40));
        usernameField.setName("Username"); // NOI18N
        usernameField.setPreferredSize(new java.awt.Dimension(250, 40));
        credentialsPanel.add(usernameField);
        credentialsPanel.add(filler3);

        emailLabel.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email");
        emailLabel.setAlignmentX(0.5F);
        credentialsPanel.add(emailLabel);

        emailField.setBackground(new java.awt.Color(117, 125, 232));
        emailField.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        emailField.setForeground(new java.awt.Color(255, 255, 255));
        emailField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailField.setBorder(null);
        emailField.setMaximumSize(new java.awt.Dimension(250, 40));
        emailField.setMinimumSize(new java.awt.Dimension(250, 40));
        emailField.setPreferredSize(new java.awt.Dimension(250, 40));
        credentialsPanel.add(emailField);
        credentialsPanel.add(filler5);

        passwordLabel.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password");
        passwordLabel.setAlignmentX(0.5F);
        credentialsPanel.add(passwordLabel);

        passwordField.setBackground(new java.awt.Color(117, 125, 232));
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordField.setBorder(null);
        passwordField.setMaximumSize(new java.awt.Dimension(250, 40));
        passwordField.setMinimumSize(new java.awt.Dimension(250, 40));
        passwordField.setPreferredSize(new java.awt.Dimension(250, 40));
        credentialsPanel.add(passwordField);

        mainPanel.add(credentialsPanel);
        mainPanel.add(filler2);

        buttonsPanel.setBackground(new java.awt.Color(63, 81, 181));
        buttonsPanel.setAlignmentY(0.0F);
        buttonsPanel.setMaximumSize(new java.awt.Dimension(1280, 100));
        buttonsPanel.setPreferredSize(new java.awt.Dimension(1280, 100));
        buttonsPanel.setLayout(new javax.swing.BoxLayout(buttonsPanel, javax.swing.BoxLayout.Y_AXIS));

        registerButton.setBackground(new java.awt.Color(0, 59, 142));
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.setAlignmentX(0.5F);
        registerButton.setBorder(null);
        registerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registerButton.setMargin(null);
        registerButton.setMaximumSize(new java.awt.Dimension(200, 50));
        registerButton.setMinimumSize(new java.awt.Dimension(200, 50));
        registerButton.setPreferredSize(new java.awt.Dimension(200, 50));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(registerButton);

        mainPanel.add(buttonsPanel);

        homeButton.setBackground(new java.awt.Color(0, 59, 142));
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setText("Home");
        homeButton.setAlignmentX(0.5F);
        homeButton.setBorder(null);
        homeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeButton.setMargin(null);
        homeButton.setMaximumSize(new java.awt.Dimension(180, 30));
        homeButton.setMinimumSize(new java.awt.Dimension(180, 30));
        homeButton.setPreferredSize(new java.awt.Dimension(180, 30));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtongoToHome(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(1088, Short.MAX_VALUE)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(736, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtongoToHome(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtongoToHome
        // TODO add your handling code here:
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.getContentPane().removeAll();
        topFrame.getContentPane().add(new MainPanel());
        topFrame.pack();
    }//GEN-LAST:event_homeButtongoToHome

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        //Register
        String username = usernameField.getText();
        String password = new String(passwordField.getPassword());
        String email = emailField.getText();
        if(username.length() < 3){
            JOptionPane.showMessageDialog(null,
                    "Username must contain at least 3 characters!",
                    "Inane error",
                    JOptionPane.ERROR_MESSAGE);
            return;
            
        }
        if(!email.contains("@") || !email.contains(".")){
            JOptionPane.showMessageDialog(null,
                    "Email not valid!",
                    "Inane error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(password.length() < 6){
            JOptionPane.showMessageDialog(null,
                    "Password must contain at least 6 characters!",
                    "Inane error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //Hash password
        String npassword = Tools.getSHA(password);
        System.out.println(password);
        try {
            MainWindow.usersList.Register(username, email, npassword);
        } catch (UserAlreadyExistsException ex) {
            JOptionPane.showMessageDialog(null,
                    "User already exists!",
                    "Inane error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(null,
                "User created!");


    }//GEN-LAST:event_registerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JPanel credentialsPanel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
